import type { AppLanguage } from "./ui";

export const exportLabels = {
  EN: {
    // P&L
    pl_title: "Profit & Loss Statement",
    pl_subtitle: "Income Statement",
    revenue: "Revenue",
    total_invoiced: "Total invoiced",
    operating_expenses: "Operating Expenses",
    total_operating: "Total operating expenses",
    operating_net: "Operating Net",
    social_charges: "Social Charges",
    social_charges_label: "SC - Social charges AVS",
    net_result: "Net Result",
    monthly_breakdown: "Monthly Breakdown",
    month: "Month",
    expenses: "Expenses",
    net: "Net",
    total: "Total",
    accounting: "Accounting",
    generated_by: "Generated by StudioManager",
    ide: "IDE",

    // Invoices list
    invoices_title: "Invoices",
    reference: "Reference",
    client: "Client",
    date: "Date",
    due_date: "Due",
    status: "Status",
    amount: "Amount",
    collected: "Collected",
    invoice: "invoice",
    invoices: "invoices",

    // Expenses list
    expenses_title: "Expenses",
    supplier: "Supplier",
    cat: "Cat.",
    paid: "Paid",
    expense: "expense",
    expenses_plural: "expenses",
    category_breakdown: "Category Breakdown",
  },
  FR: {
    // P&L
    pl_title: "Compte de resultat",
    pl_subtitle: "Profit & Loss Statement",
    revenue: "Revenus",
    total_invoiced: "Total facture",
    operating_expenses: "Frais d'exploitation",
    total_operating: "Total frais d'exploitation",
    operating_net: "Resultat d'exploitation",
    social_charges: "Charges sociales",
    social_charges_label: "CS - Charges sociales AVS",
    net_result: "Resultat net",
    monthly_breakdown: "Detail mensuel",
    month: "Mois",
    expenses: "Depenses",
    net: "Net",
    total: "Total",
    accounting: "Comptabilite",
    generated_by: "Genere par StudioManager",
    ide: "IDE",

    // Invoices list
    invoices_title: "Factures",
    reference: "Reference",
    client: "Client",
    date: "Date",
    due_date: "Echeance",
    status: "Statut",
    amount: "Montant",
    collected: "Encaisse",
    invoice: "facture",
    invoices: "factures",

    // Expenses list
    expenses_title: "Depenses",
    supplier: "Fournisseur",
    cat: "Cat.",
    paid: "Paye",
    expense: "depense",
    expenses_plural: "depenses",
    category_breakdown: "Repartition par categorie",
  },
} as const;

export type ExportLabels = { [K in keyof typeof exportLabels.EN]: string };

export function getExportLabels(lang: AppLanguage): ExportLabels {
  return exportLabels[lang] as ExportLabels;
}

const MONTHS_EN = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const MONTHS_FR = ["Jan", "Fev", "Mar", "Avr", "Mai", "Jun", "Jul", "Aou", "Sep", "Oct", "Nov", "Dec"];

export function getMonthNames(lang: AppLanguage): string[] {
  return lang === "FR" ? MONTHS_FR : MONTHS_EN;
}
