import {
  Type,
  Hash,
  CheckSquare,
  Tag,
  Tags,
  FunctionSquare,
  Clock,
  Calendar,
  User,
  FileText,
  Image,
  Video,
  Music,
  Star,
  Flag,
  Bookmark,
  Link,
  Eye,
  MessageSquare,
  Layers,
  Box,
  Palette,
  Zap,
  Target,
  AlertCircle,
  Briefcase,
  Folder,
  PenTool,
  Repeat,
  Sigma,
  BarChart2,
  DollarSign,
  Percent,
  ListChecks,
  Ruler,
  type LucideIcon,
} from "lucide-react";

export const COLUMN_ICONS: Record<string, LucideIcon> = {
  type: Type,
  hash: Hash,
  check_square: CheckSquare,
  tag: Tag,
  tags: Tags,
  function: FunctionSquare,
  clock: Clock,
  calendar: Calendar,
  user: User,
  file_text: FileText,
  image: Image,
  video: Video,
  music: Music,
  star: Star,
  flag: Flag,
  bookmark: Bookmark,
  link: Link,
  eye: Eye,
  message: MessageSquare,
  layers: Layers,
  box: Box,
  palette: Palette,
  zap: Zap,
  target: Target,
  alert: AlertCircle,
  briefcase: Briefcase,
  folder: Folder,
  pen_tool: PenTool,
  repeat: Repeat,
  sigma: Sigma,
  bar_chart: BarChart2,
  dollar: DollarSign,
  percent: Percent,
  list_checks: ListChecks,
  ruler: Ruler,
};

export const COLUMN_ICON_NAMES = Object.keys(COLUMN_ICONS);
